# Generated by Django 4.2.14 on 2026-02-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_tb',
            old_name='rule_id',
            new_name='rule',
        ),
    ]
