# Generated by Django 4.2.14 on 2026-02-19 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_rule_id_check_tb_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hozen_calendar_tb',
            name='date_tag',
            field=models.CharField(blank=True, choices=[('LONG_HOLIDAY', '連休')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hozen_calendar_tb',
            name='holiday_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hozen_calendar_tb',
            name='date_alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hozen_calendar_tb',
            name='h_day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], null=True),
        ),
        migrations.AlterField(
            model_name='hozen_calendar_tb',
            name='h_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='hozen_calendar_tb',
            name='h_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1週目'), (2, '2週目'), (3, '3週目'), (4, '4週目'), (6, '予備週')], null=True),
        ),
    ]
