# Generated by Django 4.2.14 on 2026-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hozen_calendar_tb_date_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_tb',
            name='status',
            field=models.CharField(choices=[('定期点検', '定期点検'), ('メーカ', 'メーカ'), ('廃止', '廃止'), ('日常点検', '日常点検'), ('自動化', '自動化'), ('兆候管理', '兆候管理')], default='定期点検', max_length=16),
        ),
        migrations.AlterField(
            model_name='check_tb',
            name='time_zone',
            field=models.CharField(choices=[('稼働中', '稼働中'), ('停止中', '停止中')], default='稼働中', max_length=10),
        ),
        migrations.AlterField(
            model_name='db_details_tb',
            name='status',
            field=models.CharField(choices=[('定期点検', '定期点検'), ('メーカ', 'メーカ'), ('廃止', '廃止'), ('日常点検', '日常点検'), ('自動化', '自動化'), ('兆候管理', '兆候管理')], default='定期点検', max_length=16),
        ),
        migrations.AlterField(
            model_name='planrulecondition',
            name='cond_type',
            field=models.CharField(choices=[('DAY_OF_WEEK', 'Day of week'), ('WEEK_PARITY', 'Week parity'), ('DATE_TAG', 'Date tag'), ('NEXT_DATE_TAG', 'Next date tag')], max_length=32),
        ),
    ]
