# Generated by Django 4.2.14 on 2026-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_check_tb_status_alter_check_tb_time_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_tb',
            name='safe_point',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
