# Generated by Django 4.2.14 on 2026-03-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_check_tb_safe_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_tb',
            name='assigned_affilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to='myapp.affilation_tb', verbose_name='担当班'),
        ),
    ]
