# Generated by Django 4.2.14 on 2026-03-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_plan_tb_assigned_affilation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_tb',
            name='assigned_affilation',
        ),
    ]
