# Generated by Django 4.2.14 on 2026-05-24 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_plan_tb_assigned_affilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_tb',
            name='required_person_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='required_person_count'),
        ),
        migrations.AlterField(
            model_name='check_tb',
            name='status',
            field=models.CharField(choices=[('日常点検', '日常点検'), ('定期点検', '定期点検'), ('兆候管理', '兆候管理'), ('自動化', '自動化'), ('メーカ', 'メーカ'), ('廃止', '廃止')], default='定期点検', max_length=16),
        ),
        migrations.AlterField(
            model_name='db_details_tb',
            name='status',
            field=models.CharField(choices=[('日常点検', '日常点検'), ('定期点検', '定期点検'), ('兆候管理', '兆候管理'), ('自動化', '自動化'), ('メーカ', 'メーカ'), ('廃止', '廃止')], default='定期点検', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='check_tb',
            constraint=models.CheckConstraint(check=models.Q(('required_person_count__gte', 1)), name='check_tb_required_person_count_gte_1'),
        ),
    ]
