# Generated by Django 4.2.14 on 2026-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_check_tb_required_person_count_alter_check_tb_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_details_tb',
            name='status',
            field=models.CharField(choices=[('通常', '通常'), ('メーカ', 'メーカ'), ('自動化', '自動化')], default='通常', max_length=16),
        ),
    ]
