# Generated by Django 4.2.14 on 2026-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_db_details_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_details_tb',
            name='status',
            field=models.CharField(choices=[('通常', '通常'), ('メーカ', 'メーカ'), ('自動化', '自動化'), ('廃止', '廃止')], default='通常', max_length=16),
        ),
    ]
