# Generated by Django 4.2.14 on 2026-06-01 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_db_details_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStandardHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source', models.CharField(choices=[('CARD_CREATE', 'カード追加'), ('CARD_ABOLISH', 'カード削除'), ('COMMON_ITEMS_UPDATE', '共通項目変更'), ('DETAIL_CREATE', '項目追加'), ('DETAIL_UPDATE', '項目変更'), ('DETAIL_ABOLISH', '項目削除'), ('PLAN_SYNC', '計画同期')], max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('control_no_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('machine_snapshot', models.CharField(blank=True, default='', max_length=40)),
                ('inspection_no_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('operated_by_member_id_snapshot', models.CharField(blank=True, default='', max_length=10)),
                ('operated_by_name_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('operated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_histories', to='myapp.control_tb')),
                ('inspection_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_histories', to='myapp.check_tb')),
                ('operated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_standard_history',
            },
        ),
    ]
