# Generated by Django 4.2.14 on 2026-06-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_inspectionstandardhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStandardHistoryTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('CHECK', '点検カード'), ('DETAIL', '点検項目'), ('PLAN', '計画')], max_length=16)),
                ('operation', models.CharField(choices=[('CREATE', '追加'), ('UPDATE', '変更'), ('ABOLISH', '廃止'), ('DELETE', '削除')], max_length=16)),
                ('target_pk_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('label_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('detail', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_history_targets', to='myapp.db_details_tb')),
                ('history', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='myapp.inspectionstandardhistory')),
                ('inspection_check', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_history_targets', to='myapp.check_tb')),
                ('plan', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_standard_history_targets', to='myapp.plan_tb')),
            ],
            options={
                'db_table': 'inspection_std_hist_target',
            },
        ),
    ]
