# Generated by Django 4.2.14 on 2026-06-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_inspectionstandardhistorytarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStandardHistoryFieldChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=64)),
                ('field_label', models.CharField(blank=True, default='', max_length=64)),
                ('before_value', models.TextField(blank=True, default='')),
                ('after_value', models.TextField(blank=True, default='')),
                ('before_display', models.CharField(blank=True, default='', max_length=255)),
                ('after_display', models.CharField(blank=True, default='', max_length=255)),
                ('target', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='myapp.inspectionstandardhistorytarget')),
            ],
            options={
                'db_table': 'inspection_std_hist_field',
            },
        ),
    ]
