# Generated by Django 4.2.14 on 2026-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_inspectionstandardhistoryfieldchange'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['operated_at'], name='ish_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['source', 'operated_at'], name='ish_src_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['control_no_snapshot', 'operated_at'], name='ish_ctrl_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['inspection_no_snapshot', 'operated_at'], name='ish_no_at_idx'),
        ),
    ]
