# Generated by Django 4.2.14 on 2026-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_inspectionstandardhistory_ish_at_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspectionstandardhistorytarget',
            index=models.Index(fields=['history'], name='isht_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistorytarget',
            index=models.Index(fields=['target_type', 'operation'], name='isht_type_op_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistorytarget',
            index=models.Index(fields=['target_type', 'target_pk_snapshot'], name='isht_type_pk_idx'),
        ),
    ]
