# Generated by Django 4.2.14 on 2026-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_inspectionstandardhistorytarget_isht_hist_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspectionstandardhistoryfieldchange',
            index=models.Index(fields=['target'], name='ishf_target_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistoryfieldchange',
            index=models.Index(fields=['field_name'], name='ishf_field_idx'),
        ),
    ]
