# Generated by Django 4.2.14 on 2026-06-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_inspectionstandardhistoryfieldchange_ishf_target_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_approved_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by_member_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by_member_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['leader_approved_at'], name='ish_lead_appr_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['foreman_approved_at'], name='ish_fore_appr_at_idx'),
        ),
    ]
