# Generated by Django 4.2.14 on 2026-06-16 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_inspectionstandardhistory_foreman_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_at',
            field=models.DateTimeField(blank=True, db_column='foreman_appr_at', null=True),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by',
            field=models.ForeignKey(blank=True, db_column='foreman_appr_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_approved_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by_member_id_snapshot',
            field=models.CharField(blank=True, db_column='foreman_appr_member_id', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='foreman_approved_by_name_snapshot',
            field=models.CharField(blank=True, db_column='foreman_appr_name', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, db_column='leader_appr_at', null=True),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by',
            field=models.ForeignKey(blank=True, db_column='leader_appr_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by_member_id_snapshot',
            field=models.CharField(blank=True, db_column='leader_appr_member_id', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inspectionstandardhistory',
            name='leader_approved_by_name_snapshot',
            field=models.CharField(blank=True, db_column='leader_appr_name', default='', max_length=20),
        ),
    ]
