# Generated by Django 4.2.14 on 2026-06-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_inspectionstandardhistory_foreman_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_tb',
            name='planned_affilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_plans', to='myapp.affilation_tb'),
        ),
    ]
