# Generated by Django 4.2.14 on 2026-06-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_plan_tb_planned_affilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='team_leader_approved_at',
            field=models.DateTimeField(blank=True, db_column='team_leader_appr_at', null=True),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='team_leader_approved_by',
            field=models.ForeignKey(blank=True, db_column='team_leader_appr_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader_approved_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='team_leader_approved_by_member_id_snapshot',
            field=models.CharField(blank=True, db_column='team_leader_appr_member_id', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='team_leader_approved_by_name_snapshot',
            field=models.CharField(blank=True, db_column='team_leader_appr_name', default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inspectionstandardhistory',
            index=models.Index(fields=['team_leader_approved_at'], name='ish_team_lead_appr_at_idx'),
        ),
    ]
