# Generated by Django 4.2.14 on 2026-07-14 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_inspectionstandardhistory_team_leader_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_column='cancelled_at', null=True),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_column='cancelled_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_inspection_standard_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='cancelled_by_member_id_snapshot',
            field=models.CharField(blank=True, db_column='cancelled_member_id', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inspectionstandardhistory',
            name='cancelled_by_name_snapshot',
            field=models.CharField(blank=True, db_column='cancelled_name', default='', max_length=20),
        ),
    ]
