# Generated by Django 4.2.14 on 2026-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_inspectionstandardhistory_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsRackLocation_tb',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rack_no', models.CharField(db_column='RACK_NO', max_length=20, unique=True, verbose_name='棚No')),
                ('location_name', models.CharField(db_column='LOCATION_NAME', max_length=200, verbose_name='保管場所')),
                ('location_note', models.CharField(blank=True, db_column='LOCATION_NOTE', default='', max_length=300, verbose_name='補足')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True, verbose_name='使用中')),
                ('display_order', models.PositiveIntegerField(db_column='DISPLAY_ORDER', default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '部品棚保管場所',
                'verbose_name_plural': '部品棚保管場所',
                'db_table': 'PARTS_RACK_LOCATION',
                'ordering': ('display_order', 'rack_no'),
            },
        ),
    ]
