# Generated by Django 4.2.14 on 2026-08-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_partsracklocation_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=32, unique=True, verbose_name='設備グループコード')),
                ('group_name', models.CharField(max_length=100, verbose_name='設備グループ名')),
                ('group_type', models.CharField(choices=[('SINGLE_EQUIPMENT', '単独設備'), ('MACHINE_SYSTEM', '主設備・付帯設備群'), ('PROCESS_SYSTEM', '工程設備群'), ('FUNCTION_GROUP', '機能別設備群'), ('SAFETY_SYSTEM', '安全・防災設備群')], max_length=32, verbose_name='設備グループ種別')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '設備グループ',
                'verbose_name_plural': '設備グループ',
                'db_table': 'equipment_group',
                'ordering': ('group_code',),
            },
        ),
        migrations.CreateModel(
            name='InstructionCardEquipmentMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=100, unique=True, verbose_name='指示カード設備名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('equipment_group', models.ForeignKey(blank=True, db_column='equipment_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_card_equipment_maps', to='myapp.equipmentgroup', verbose_name='設備グループ')),
            ],
            options={
                'verbose_name': '指示カード設備名マップ',
                'verbose_name_plural': '指示カード設備名マップ',
                'db_table': 'instruction_card_equipment_map',
                'ordering': ('equipment_name',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentGroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_role', models.CharField(choices=[('MAIN_MACHINE', '主設備'), ('CONTROL_PANEL', '制御盤'), ('ROBOT', 'ロボット'), ('CONVEYOR', '搬送設備'), ('TEMPERATURE_UNIT', '温調設備'), ('AIR_CONDITIONING', '給排気・空調設備'), ('DRYING_OVEN', '乾燥炉'), ('AGV', 'AGV'), ('SAFETY_DEVICE', '安全・防災設備'), ('UTILITY', '付帯設備'), ('OTHER', 'その他設備')], max_length=32, verbose_name='設備役割')),
                ('is_primary', models.BooleanField(default=False, verbose_name='代表設備')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('control', models.ForeignKey(db_column='control_id', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_group_members', to='myapp.control_tb', verbose_name='個別設備')),
                ('equipment_group', models.ForeignKey(db_column='equipment_group_id', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='myapp.equipmentgroup', verbose_name='設備グループ')),
            ],
            options={
                'verbose_name': '設備グループ所属設備',
                'verbose_name_plural': '設備グループ所属設備',
                'db_table': 'equipment_group_member',
                'ordering': ('equipment_group__group_code', '-is_primary', 'control__control_no'),
            },
        ),
        migrations.AddIndex(
            model_name='equipmentgroup',
            index=models.Index(fields=['group_type', 'is_active'], name='eqgrp_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentgroupmember',
            index=models.Index(fields=['equipment_group', 'is_active'], name='eqgrp_mem_group_act_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentgroupmember',
            index=models.Index(fields=['control', 'is_active'], name='eqgrp_mem_ctrl_act_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentgroupmember',
            index=models.Index(fields=['member_role'], name='eqgrp_mem_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentgroupmember',
            constraint=models.UniqueConstraint(fields=('control',), name='eqgrp_mem_control_uq'),
        ),
        migrations.AddConstraint(
            model_name='equipmentgroupmember',
            constraint=models.CheckConstraint(check=models.Q(('is_primary', False), ('is_active', True), _connector='OR'), name='eqgrp_mem_primary_act_ck'),
        ),
    ]
