# Generated by Django 4.2.14 on 2026-08-05 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_equipmentgroup_instructioncardequipmentmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(default='PLUS ULTRA_Ver8.csv', max_length=150, verbose_name='取込元ファイル名')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='取込元行番号')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='旧指示カードID')),
                ('issued_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='発行日')),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=50, verbose_name='From')),
                ('process_name', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工程名')),
                ('equipment_name', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='設備名')),
                ('maintenance_type', models.CharField(blank=True, choices=[('予防', '予防'), ('事後', '事後'), ('その他', 'その他'), ('改良', '改良'), ('現場依頼', '現場依頼'), ('調査', '調査'), ('生技依頼', '生技依頼'), ('安全', '安全'), ('人材育成', '人材育成')], db_index=True, default='', max_length=16, verbose_name='保全区分')),
                ('work_name', models.CharField(blank=True, default='', max_length=150, verbose_name='作業名')),
                ('planned_person_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='予定人数')),
                ('planned_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='予定工数・分')),
                ('request_text', models.TextField(blank=True, default='', verbose_name='依頼内容')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='期日')),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=50, verbose_name='To')),
                ('related_document_before', models.TextField(blank=True, default='', verbose_name='関連資料1')),
                ('card_reference', models.TextField(blank=True, default='', verbose_name='カードNo・参照先')),
                ('completion_status', models.CharField(blank=True, choices=[('完了', '完了'), ('実施待ち', '実施待ち'), ('保留', '保留')], db_index=True, default='', max_length=16, verbose_name='完了フラグ')),
                ('action_text', models.TextField(blank=True, default='', verbose_name='実施内容')),
                ('actual_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='実施工数・分')),
                ('work_reflection', models.TextField(blank=True, default='', verbose_name='作業の振り返り')),
                ('injury_state', models.TextField(blank=True, default='', verbose_name='ケガの状態')),
                ('injury_cause', models.TextField(blank=True, default='', verbose_name='ケガの要因')),
                ('unsafe_condition', models.TextField(blank=True, default='', verbose_name='不安全状態')),
                ('unsafe_action', models.TextField(blank=True, default='', verbose_name='不安全行動')),
                ('ky_risk_identification', models.TextField(blank=True, default='', verbose_name='洗い出しKY')),
                ('safety_measure_1', models.TextField(blank=True, default='', verbose_name='安全対策1')),
                ('safety_measure_2', models.TextField(blank=True, default='', verbose_name='安全対策2')),
                ('safety_measure_3', models.TextField(blank=True, default='', verbose_name='安全対策3')),
                ('pointing_call', models.TextField(blank=True, default='', verbose_name='指差呼称')),
                ('priority_risk_point', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='重点危険ポイント')),
                ('nine_word_flags', models.JSONField(blank=True, default=list, verbose_name='9ワード')),
                ('related_document_after', models.TextField(blank=True, default='', verbose_name='実施後関連資料')),
                ('replacement_part_1', models.CharField(blank=True, default='', max_length=150, verbose_name='交換部品1')),
                ('replacement_part_2', models.CharField(blank=True, default='', max_length=150, verbose_name='交換部品2')),
                ('standalone_operation_ok', models.BooleanField(blank=True, null=True, verbose_name='単体動作')),
                ('interlocked_operation_ok', models.BooleanField(blank=True, null=True, verbose_name='連動動作')),
                ('quality_ok', models.BooleanField(blank=True, null=True, verbose_name='品質')),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='完了日')),
                ('completed_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='完了時')),
                ('completed_minute', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='完了分')),
                ('actual_person_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='実施人数')),
                ('issuing_team_leader_name', models.CharField(blank=True, default='', max_length=50, verbose_name='発行班長')),
                ('a_team_leader_name', models.CharField(blank=True, default='', max_length=50, verbose_name='A班長')),
                ('b_team_leader_name', models.CharField(blank=True, default='', max_length=50, verbose_name='B班長')),
                ('c_team_leader_name', models.CharField(blank=True, default='', max_length=50, verbose_name='C班長')),
                ('group_leader_name', models.CharField(blank=True, default='', max_length=50, verbose_name='組長')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取込日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('equipment_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_cards', to='myapp.instructioncardequipmentmap', verbose_name='指示カード設備名マップ')),
            ],
            options={
                'verbose_name': '指示カード',
                'verbose_name_plural': '指示カード',
                'db_table': 'instruction_card',
                'ordering': ('-issued_date', '-id'),
                'indexes': [models.Index(fields=['equipment_map', 'issued_date'], name='inst_card_eqmap_date_idx'), models.Index(fields=['maintenance_type', 'completion_status'], name='inst_card_type_stat_idx'), models.Index(fields=['process_name', 'equipment_name'], name='inst_card_proc_eq_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='instructioncard',
            constraint=models.UniqueConstraint(fields=('source_file_name', 'source_row_number'), name='inst_card_source_row_uq'),
        ),
        migrations.AddConstraint(
            model_name='instructioncard',
            constraint=models.CheckConstraint(check=models.Q(('completed_hour__isnull', True), models.Q(('completed_hour__gte', 0), ('completed_hour__lte', 23)), _connector='OR'), name='inst_card_hour_ck'),
        ),
        migrations.AddConstraint(
            model_name='instructioncard',
            constraint=models.CheckConstraint(check=models.Q(('completed_minute__isnull', True), models.Q(('completed_minute__gte', 0), ('completed_minute__lte', 59)), _connector='OR'), name='inst_card_minute_ck'),
        ),
        migrations.AddConstraint(
            model_name='instructioncard',
            constraint=models.CheckConstraint(check=models.Q(('priority_risk_point__isnull', True), models.Q(('priority_risk_point__gte', 1), ('priority_risk_point__lte', 4)), _connector='OR'), name='inst_card_risk_point_ck'),
        ),
    ]
