# Generated by Django 4.2.14 on 2026-09-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_instructioncard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanScheduleChangeHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("MOVE", "予定移動")],
                        default="MOVE",
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("plan_id_snapshot", models.PositiveIntegerField()),
                ("source_date_snapshot", models.DateField()),
                ("source_affiliation_id_snapshot", models.PositiveIntegerField()),
                ("source_affiliation_name_snapshot", models.CharField(max_length=20)),
                ("source_shift_pattern_id_snapshot", models.PositiveIntegerField()),
                ("source_shift_name_snapshot", models.CharField(max_length=20)),
                ("destination_date_snapshot", models.DateField()),
                ("destination_affiliation_id_snapshot", models.PositiveIntegerField()),
                ("destination_affiliation_name_snapshot", models.CharField(max_length=20)),
                ("destination_shift_pattern_id_snapshot", models.PositiveIntegerField()),
                ("destination_shift_name_snapshot", models.CharField(max_length=20)),
                ("changed_by_member_id_snapshot", models.CharField(max_length=10)),
                ("changed_by_name_snapshot", models.CharField(max_length=20)),
                ("organization_code_snapshot", models.CharField(max_length=10)),
                ("organization_name_snapshot", models.CharField(max_length=10)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_schedule_change_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_affiliation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_plan_schedule_changes",
                        to="myapp.affilation_tb",
                    ),
                ),
                (
                    "destination_date",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_plan_schedule_changes",
                        to="myapp.hozen_calendar_tb",
                    ),
                ),
                (
                    "destination_shift_pattern",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_plan_schedule_changes",
                        to="myapp.shiftpattan_tb",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_schedule_change_histories",
                        to="myapp.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_change_histories",
                        to="myapp.plan_tb",
                    ),
                ),
                (
                    "source_affiliation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_plan_schedule_changes",
                        to="myapp.affilation_tb",
                    ),
                ),
                (
                    "source_date",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_plan_schedule_changes",
                        to="myapp.hozen_calendar_tb",
                    ),
                ),
                (
                    "source_shift_pattern",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_plan_schedule_changes",
                        to="myapp.shiftpattan_tb",
                    ),
                ),
            ],
            options={
                "db_table": "plan_schedule_change_history",
                "indexes": [
                    models.Index(fields=["plan", "changed_at"], name="psch_plan_at_idx"),
                    models.Index(fields=["changed_at"], name="psch_at_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            ~models.Q(
                                source_date_snapshot=models.F("destination_date_snapshot")
                            )
                            | ~models.Q(
                                source_affiliation_id_snapshot=models.F(
                                    "destination_affiliation_id_snapshot"
                                )
                            )
                        ),
                        name="psch_source_dest_diff",
                    ),
                    models.CheckConstraint(
                        check=models.Q(change_type="MOVE"),
                        name="psch_move_type",
                    ),
                ],
            },
        ),
    ]
