PLAN_STATUS_COMPLETED = "完了"
PLAN_STATUS_WAITING   = "実施待ち"
PLAN_STATUS_PENDING   = "配布待ち"
PLAN_STATUS_DELAY     = "遅れ" 

PLAN_STATUSES = {
    PLAN_STATUS_COMPLETED,
    PLAN_STATUS_WAITING,
    PLAN_STATUS_PENDING,
    PLAN_STATUS_DELAY,
}

PLAN_STATUSES_ORDERED = (
    PLAN_STATUS_PENDING,
    PLAN_STATUS_WAITING,
    PLAN_STATUS_DELAY,
    PLAN_STATUS_COMPLETED,
)